version: "3"

services:

  mysqldb:
      container_name: kata10db
      image: mysql
      ports:
        - 3307:3306
      environment:
        MYSQL_DATABASE: web_site_2
        MYSQL_ROOT_PASSWORD: root
